### ISSUE TITLE
Sweet!!! 2.80 dev version

### ISSUE THREAD

**Issue by schroef** [Exairnous/Advanced-UI-Menus#9]
Nice i see you are working on 2.80 version. I miss this one so bad!

PS did you also add all the stuff we were talking about in that other [thread](https://github.com/Exairnous/Advanced-UI-Menus/issues/1)?

**Comment by schroef** [comment]
I do get some errors. I think the dev version repo name is causing some issues here.

Are you using the same sort method of Magic UV to make it backwards compatible orso?
I see an error and think this for converting the attributes isnt it?

```
Traceback (most recent call last):
  File "/Applications/blender-2.80.0-git20190215.faa255c0a4e4-x86_64/blender.app/Contents/Resources/2.80/scripts/modules/addon_utils.py", line 393, in enable
    mod.register()
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.80/scripts/addons/Advanced-UI-Menus/__init__.py", line 82, in register
    addon_file.register()
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.80/scripts/addons/Advanced-UI-Menus/custom_menu.py", line 876, in register
    update=update_args
  File "/Users/romboutversluijs/Library/Application Support/Blender/2.80/scripts/addons/Advanced-UI-Menus/Utils/core.py", line 148, in set_prop
    exec("from {0} import {1}".format(v.__module__, v.__name__))
  File "<string>", line 1
    from Advanced-UI-Menus.custom_menu import update_args

```

**Comment by schroef** [comment]
Funny thing is it seems the dashes in the addons name is causing this error. I changed 'Advanced-UI-Menus' to 'Advanced_UI_Menu'  and than it actives without errors.

But i guess its still WIP, i get tons of other errors now.

**Comment by schroef** [comment]
Its bizar how much they changed, im wondering what the benefit is from this. They've renamed so many items in the api... pfffff i was just check the view_menu and pivot_menu. I got pivot_menu working now but view_menu keeps throwing errors at me.

**Comment by schroef** [comment]
Okay i got view_menu, pivot_menu and snap_menu working :)

<img width="446" alt="screen shot 2019-02-21 at 20 39 57" src="https://user-images.githubusercontent.com/6923008/53211814-f17b1080-3618-11e9-9e2c-b898ee94027f.png">
<img width="502" alt="screen shot 2019-02-21 at 20 39 49" src="https://user-images.githubusercontent.com/6923008/53211815-f17b1080-3618-11e9-9479-5c4e815bffde.png">
<img width="310" alt="screen shot 2019-02-21 at 21 22 02" src="https://user-images.githubusercontent.com/6923008/53213296-c398ca80-361e-11e9-9cdf-2f99d341113c.png">

**Comment by Exairnous** [comment]
> Nice i see you are working on 2.80 version. I miss this one so bad!

:smiley: :smiley: :smiley: 

> PS did you also add all the stuff we were talking about in that other [thread](https://github.com/Exairnous/Advanced-UI-Menus/issues/1)?

We had a couple of unresolved issues and I've been busy with other things, so no :smiley:.  I'll take this as a go ahead and add them to the next release.

> Are you using the same sort method of Magic UV to make it backwards compatible orso?

Nope.  The plan is to maintain a 2.79b and a separate 2.80 version

> Funny thing is it seems the dashes in the addons name is causing this error. I changed 'Advanced-UI-Menus' to 'Advanced_UI_Menu' and than it actives without errors.
> 
> But i guess its still WIP, i get tons of other errors now.

Yep!  Very much still a WIP.  It shouldn't matter, but I'll have a look at the name error sometime.  Thanks for telling me.

> Okay i got view_menu, pivot_menu and snap_menu working :)

Nice!  Most of the porting should be pretty easy, if you want send me a pull request, but try to avoid whitespace changes.  Indent is 4 spaces.

For the switch to 2.80 I'm probably going to do some major cleanup/refactoring to both the 2.80 and 2.79b versions, but that'll mostly come after everything is working on 2.8 with current systems.

If I missed something I should've responded to just let me know and thanks for the continued interest. :smiley:

**Comment by Exairnous** [comment]
@schroef 2.8 port is almost complete!  No new menus for Grease Pencil, they may not end up in the first release depending on time, but I think everything else has been ported.  Can you please test? 
Thanks.

Oh, and I figured out about the name error.  It's because python views dashes as the subtraction operator and I didn't think about that when I was naming the GitHub repo (which uses the repo name as the folder name).  GitHub also adds a dash and the branch name to any zips you download, so I can't solve the problem completely, but sometime I'll see what I can do to make it better.

Enjoy! :smile:

**Comment by schroef** [comment]
Okay ill check this repo, i havent done much with Bl 280, simply did check updates and every Monday video on youtube. Havent really used it that much.

Quite some keystrokes overlap now i think. But thats is not that hard to overcome, having that key hold option is also an option.

Some items are changed completely like manipulator? did you solve that somehow? They added this with enum menu which is completely vague to me what it does? I find some of there adjustments so weird and when asked about, its like talking to a wall ;) 

Should i test current version or wait till its complete?

**Comment by Exairnous** [comment]
I don't think there is any major keymap overlap (check the readme for new keys), but let me know if you see any.  I did something with the manipulator, not sure it's the best solution (it doesn't use the new tools), but it works somewhat; let me know if you have any ideas for it.  Test the current version.  The only thing that will change is bug fixing, :wink:, and adding grease pencil support if I have time.
